### ISSUE TITLE
Support localhost urls

### ISSUE THREAD

**Issue by arunoda** [vercel/fetch-cached-dns#3]
When fetching urls with localhost, we receive errors like this:

```
Ms-MacBook-Pro:worker arunoda$ npm run testonly -- -t "create jobs"

> @zeit/atlas-worker@0.12.0 testonly /data/zeit/atlas/worker
> WARN_EXIT=1 jest --coverage -i --verbose --forceExit "-t" "create jobs"

 FAIL  test/worker.js (9.839s)
  ● create jobs

    queryA ENOTFOUND localhost

      at errnoException (dns.js:53:10)
      at QueryReqWrap.onresolve [as oncomplete] (dns.js:241:19)

  ● create jobs (http)

    queryA ENOTFOUND localhost

      at errnoException (dns.js:53:10)
      at QueryReqWrap.onresolve [as oncomplete] (dns.js:241:19)

  ✕ create jobs (5155ms)
  ✕ create jobs (http) (4075ms)
  ○ skipped 21 tests

Test Suites: 1 failed, 7 skipped, 1 of 8 total
Tests:       2 failed, 46 skipped, 48 total
Snapshots:   0 total
Time:        10.748s, estimated 48s
```

**Comment by raduflp** [comment]
I can confirm that this issue persists to this day

**Comment by jamo** [comment]
This has been fixed in [@OlliV/fetch](https://www.npmjs.com/package/@olliv/fetch)
